var info = [{username: "Neryia", password: "Nd123123", nickname: "shupi", profPic: "./neriya.png",
             chats:[{user: "Avraham", msgArr:[{type: "image", data: "./problem_meme.jpg", time: { month: "3", day: "23", hour: "12:30"}, side: 0},
                                              {type: "text", data: "hi", time: { month: "3", day: "23", hour: "12:40"}, side: 1}]},
                    {user: "Tamir", msgArr:[{type: "text", data: "awake?", time: { month: "3", day: "23", hour: "03:30"}, side: 0},
                                            {type: "audio", data: "./stam.mp3", time: { month: "3", day: "23", hour: "09:45"}, side: 1}]},
                    {user: "Elad", msgArr:[{type: "video", data: "./toilet.mp4", time: { month: "3", day: "23", hour: "12:30"}, side: 1},
                                           {type: "text", data: "who are you", time: { month: "3", day: "23", hour: "12:40"}, side: 0}]}]},       
            {username: "Avraham", password: "Ab123123", nickname: "avi", profPic: "./avi.png", 
             chats:[{user: "Neryia", msgArr:[{type: "image", data: "./problem_meme.jpg", time: { month: "3", day: "23", hour: "12:30"}, side: 1},
                                            {type: "text", data: "hi", time: { month: "3", day: "24", hour: "12:40"}, side: 0}]},
                    {user: "Matan", msgArr:[{type: "text", data: "what?", time: { month: "3", day: "23", hour: "07:30"}, side: 0},
                                            {type: "text", data: "never", time: { month: "3", day: "23", hour: "09:45"}, side: 1}]},
                    {user: "Elad", msgArr:[{type: "text", data: "are you doneeeeeeeeeeeeeeeeeeeeeee???", time: { month: "3", day: "23", hour: "12:30"}, side: 1},
                                           {type: "text", data: "who are you", time: { month: "2", day: "27", hour: "12:40"}, side: 0}]}]},
            {username: "Matan", password: "Ms123123", nickname: "matan :)", profPic: "./matan.png", 
             chats:[{user: "Avraham", msgArr:[{type: "text", data: "what?", time: { month: "3", day: "23", hour: "07:30"}, side: 1},
                                            {type: "text", data: "never", time: { month: "3", day: "23", hour: "09:45"}, side: 0}]},
                    {user: "Nikol", msgArr:[{type: "text", data: "awake?", time: { month: "3", day: "23", hour: "03:30"}, side: 0},
                                            {type: "text", data: "no", time: { month: "3", day: "23", hour: "09:45"}, side: 1}]},
                    {user: "Elad", msgArr:[{type: "text", data: "can i get some help?", time: { month: "3", day: "23", hour: "12:30"}, side: 1},
                                           {type: "text", data: "yeah why not", time: { month: "3", day: "23", hour: "12:40"}, side: 0}]}]},
            {username: "Nikol", password: "Ne123123", nickname: "niki", profPic: "./g.png", 
             chats:[{user: "Tamir", msgArr:[{type: "audio", data: "./shir.mp3", time: { month: "3", day: "23", hour: "12:30"}, side: 0},
                                              {type: "text", data: "hi", time: { month: "3", day: "23", hour: "12:40"}, side: 1}]},
                    {user: "Matan", msgArr:[{type: "text", data: "awake?", time: { month: "3", day: "23", hour: "03:30"}, side:1},
                                            {type: "text", data: "no", time: { month: "3", day: "23", hour: "09:45"}, side: 0}]}]},
            {username: "Elad", password: "Eb123123", nickname: "balie", profPic: "./g.png", 
             chats:[{user: "Avraham", msgArr:[{type: "text", data: "are you doneeeeeeeeeeeeeeeeeeeeeee???", time: { month: "3", day: "23", hour: "12:30"}, side:0},
                                            {type: "text", data: "who are you", time: { month: "2", day: "27", hour: "12:40"}, side:10}]},
                    {user: "Matan", msgArr:[{type: "text", data: "can i get some help?", time: { month: "3", day: "23", hour: "12:30"}, side: 0},
                                            {type: "text", data: "yeah why not", time: { month: "3", day: "23", hour: "12:40"}, side: 1}]},
                    {user: "Neryia", msgArr:[{type: "video", data: "./toilet.mp4", time: { month: "3", day: "23", hour: "12:30"}, side: 0},
                                             {type: "text", data: "who are you", time: { month: "3", day: "23", hour: "12:40"}, side: 1}]}]},
            {username: "Tamir", password: "Ty123123", nickname: "yoshi", profPic: "./g.png", 
             chats:[{user: "Nikol", msgArr:[{type: "audio", data: "./shir.mp3", time: { month: "3", day: "23", hour: "12:30"}, side: 1},
                                             {type: "text", data: "hi", time: { month: "3", day: "23", hour: "12:40"}, side: 0}]},
                    {user: "Neryia", msgArr:[{type: "text", data: "awake?", time: { month: "3", day: "23", hour: "03:30"}, side: 1},
                                            {type: "audio", data: "./stam.mp3", time: { month: "3", day: "23", hour: "09:45"}, side: 0}]},
                    {user: "Avraham", msgArr:[{type: "text", data: "yoshi as in avatar kyoshi?", time: { month: "3", day: "23", hour: "12:30"}, side: 1},
                                              {type: "text", data: "who are you?", time: { month: "3", day: "23", hour: "12:40"}, side: 0}]}]}];

export default info;
// side: 0=you, 1=other.
// months are 0-11 (so "may" is the number '4')